typography_spectrum: 0.9130053329281509
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3890134624671191
  lightness: 0.05764238350093365
  saturation: 0.22003324329853058
  rhythmicContrast: 0.18810613732784986
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.364445622311905
analytics:
  google: 52.32.215.222
  facebook: null
  twitter: null
name: Eye To The World
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 'Stay '
    url: 'https://about.me/cultureme'
    type: external
favicon: null
title: We Came To Thrive
purpose: []
